### ISSUE TITLE
WalletCoinsReceivedEventListener.onCoinsReceived() not receiving events

### ISSUE THREAD

**Issue by avlo** [pokkst/litecoinj#5]
has anyone else experienced this and have a solution?  i have an identical implementation that works fine using bitcoinj/network.

**Comment by pokkst** [comment]
What does your setup look like? Are you accepting risky transactions? I think by default bitcoinj (and consequently litecoinj) does not show unconfirmed coins in your balance.

It seems obvious, but are you for sure adding the event listener to the wallet correctly?

**Comment by pokkst** [comment]
> confirmations are handled differently and separately than WalletCoinsReceivedEventListener.onCoinsReceived(), the latter is where the issue is.

Yes, but depending on how your actual litecoinj wallet is set up, onCoinsReceived may not be called until there is confirmation on the transaction.

**Comment by avlo** [comment]
> Yes, but depending on how your actual litecoinj wallet is set up, onCoinsReceived may not be called until there is confirmation on the transaction.

the wallet setup is the default setup, and can be seen [here](https://github.com/avlo/hitopbtc/blob/0025-add_litecoin/src/main/java/com/hitop/AppConfig.java#L91) (which is exactly the same as bitcoin on line 58).  is there perhaps something additional/different that must be done for litecoin?

**Comment by avlo** [comment]
issue solved.  the manner in which i was obtaining a fresh litecoin receive address followed a pattern used by legacy btc addresses, but was not necessary for litecoin.
