### ISSUE TITLE
TestNet dnsSeeds do not seem to exist

### ISSUE THREAD

**Issue by doc-ef** [pokkst/litecoinj#8]
The TestNet3Params has 3 dns names hardcoded in for the dnsSeed array values (below).  NONE of these 3 dns names even resolve anymore, let alone ping/work.  If I use the MainNetParams everything works fine (albeit a good 30 minute first time load of Wallet/WalletKit to sync spv chain).    If there are updated testnet config values, would be great if these were merged in.  If LiteCoin testnet just not supported/working anymore, that would be nice to know as well.

        dnsSeeds = new String[] {
                "testnet-seed.litecointools.com",
                "seed-b.litecoin.loshan.co.uk",
                "dnsseed-testnet.thrasher.io"
        };

**Comment by ygk44** [comment]
All 3 seeders are down. loshan and thrasher seem to be working to get them back.
https://litecointalk.io/t/does-litecoin-testnet-work-and-if-so-what-are-the-dns-seed-addresses-that-work/53052/2

**Comment by pokkst** [comment]
These are the only seeders listed in the main Litecoin Core codebase for testnet, and they still seem to be down/returning nothing. Not much I can do (I don't have intentions of running my own)
